// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlc

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_code)
VALUES ($1, $2)
RETURNING original_url, short_code
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortCode   string `json:"short_code"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortCode)
	var i Link
	err := row.Scan(&i.OriginalUrl, &i.ShortCode)
	return i, err
}

const getLinkByOriginalURL = `-- name: GetLinkByOriginalURL :one
SELECT original_url, short_code
FROM links
WHERE original_url = $1
`

func (q *Queries) GetLinkByOriginalURL(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByOriginalURL, originalUrl)
	var i Link
	err := row.Scan(&i.OriginalUrl, &i.ShortCode)
	return i, err
}

const getLinkByShortCode = `-- name: GetLinkByShortCode :one
SELECT original_url, short_code
FROM links
WHERE short_code = $1
`

func (q *Queries) GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortCode, shortCode)
	var i Link
	err := row.Scan(&i.OriginalUrl, &i.ShortCode)
	return i, err
}
