// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MocklinkService is a mock of linkService interface.
type MocklinkService struct {
	ctrl     *gomock.Controller
	recorder *MocklinkServiceMockRecorder
}

// MocklinkServiceMockRecorder is the mock recorder for MocklinkService.
type MocklinkServiceMockRecorder struct {
	mock *MocklinkService
}

// NewMocklinkService creates a new mock instance.
func NewMocklinkService(ctrl *gomock.Controller) *MocklinkService {
	mock := &MocklinkService{ctrl: ctrl}
	mock.recorder = &MocklinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklinkService) EXPECT() *MocklinkServiceMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MocklinkService) CreateLink(ctx context.Context, originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MocklinkServiceMockRecorder) CreateLink(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MocklinkService)(nil).CreateLink), ctx, originalURL)
}

// ResolveLink mocks base method.
func (m *MocklinkService) ResolveLink(ctx context.Context, shortCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveLink", ctx, shortCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveLink indicates an expected call of ResolveLink.
func (mr *MocklinkServiceMockRecorder) ResolveLink(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveLink", reflect.TypeOf((*MocklinkService)(nil).ResolveLink), ctx, shortCode)
}
